baseURL = "https://kathrynstephens.co.uk"
defaultContentLanguage = "en"
languageCode = "en-us"
theme = "papercss-hugo-theme"
title = "Kat's Thoughts"
[imaging]
quality = 99
[[menu.nav]]
name = "About"
url = "/about/"
weight = 3
[[menu.nav]]
name = "Tags"
url = "/tags/"
weight = 2
[[menu.nav]]
name = "Blog"
url = "/"
weight = 1
[params]
navTitleLink = "/"
[permalinks]
[privacy.disqus]
[taxonomies]
tag = "tags"
